/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2026-08-10 05:52:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Inspection_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1660696354000L));
    _jspx_dependants.put("jar:file:/daejist7/tomcat/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/daejist7/tomcat/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html style=\"height: 100%;\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>검수</title>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\" media=\"screen\" title=\"no title\" charset=\"utf-8\">\r\n");
      out.write("    <script src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("    <!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.11.1.min.js\" type=\"text/javascript\"></script> -->\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <!-- <script src=\"js/bootstrap.min.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <!-- <script src=\"js/bootstrap.min.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    \t.btn-default:hover{\r\n");
      out.write("    \t\tbackground-color: black;\r\n");
      out.write("    \t\tcolor:white;\r\n");
      out.write("    \t\tborder: solid 1px white;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t.dropdown {\r\n");
      out.write("\t\t    position: relative;\r\n");
      out.write("\t\t    display: inline-block;\r\n");
      out.write("\t\t    background-color: white;\r\n");
      out.write("\t\t    color: black;\r\n");
      out.write("\t\t    width: 98%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.dropdown-content {\r\n");
      out.write("\t\t\tcolor:black;\r\n");
      out.write("\t\t\tlist-style:none;\r\n");
      out.write("\t\t    background-color: white;\r\n");
      out.write("\t\t    overflow: auto;\r\n");
      out.write("\t\t    z-index: 1;\r\n");
      out.write("\t\t    width: 98%;\r\n");
      out.write("\t\t    height: 100px;\r\n");
      out.write("\t\t    text-align: left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.dropdown-content li:hover {background-color: #ddd;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.clickDropDown {\r\n");
      out.write("\t\t\tdisplay:none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.font_normal{\r\n");
      out.write("\t\t\tfont-weight: normal;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.drop_selBox{\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t    display: none;\r\n");
      out.write("\t\t    background-color: white;\r\n");
      out.write("\t\t    color: black;\r\n");
      out.write("\t\t    width: 92%;\r\n");
      out.write("\t        height: 100px;\r\n");
      out.write("\t\t    padding: 0 0;\r\n");
      out.write("\t        margin-left: 0.8%;\r\n");
      out.write("    \t\toverflow: auto;\r\n");
      out.write("   \t\t    z-index: 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.drop_selBox li{\r\n");
      out.write("\t\t\tcolor:black;\r\n");
      out.write("\t\t\tlist-style:none;\r\n");
      out.write("\t\t    background-color: white;\r\n");
      out.write("\t\t    overflow: auto;\r\n");
      out.write("\t\t    width: 98%;\r\n");
      out.write("\t\t    text-align: left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.drop_selBox li:hover{\r\n");
      out.write("\t\t\tbackground-color: #ddd;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.pro_sel_box{\r\n");
      out.write("\t\t\twidth: 98%;\r\n");
      out.write("\t\t\t/* position: relative; */\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var doact = {\r\n");
      out.write("\t\tuserCd : \"\",\r\n");
      out.write("\t\tuserNm : \"\"\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setBoundData(param, valueID, gb){\r\n");
      out.write("\tvar tagName = $('#' + valueID)[0].tagName;\r\n");
      out.write("\t\r\n");
      out.write("\t   var value = param;\r\n");
      out.write("\t   var data = {};\r\n");
      out.write("\t   data[\"sVal\"] = value;\r\n");
      out.write("\t   data[\"sGb\"] = gb;\r\n");
      out.write("\t   \r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t      url: \"getInboundData.do\",\r\n");
      out.write("\t      type: \"POST\",\r\n");
      out.write("\t      //contentType : \"application/text; charset=utf-8\",\r\n");
      out.write("\t      //dataType: \"JSON\",\r\n");
      out.write("\t      data: {\"data\":JSON.stringify(data)},\r\n");
      out.write("\t      success: function(data){\r\n");
      out.write("\t         var cvtData = data.data;\r\n");
      out.write("\t         var jsonArrObj = $.parseJSON('[' + JSON.stringify(cvtData) + ']');\r\n");
      out.write("\t         var id = valueID;\r\n");
      out.write("\t         \r\n");
      out.write("\t         if(tagName == \"SELECT\"){\r\n");
      out.write("\t\t         if(jsonArrObj.length > 0){\r\n");
      out.write("\t\t            $('#' + id).find(\"option\").remove().end().append(\"<option value=>선택</option>\");\r\n");
      out.write("\t\t            $.each(jsonArrObj, function(index, item){\r\n");
      out.write("\t\t               $(item).each(function (key, value) {\r\n");
      out.write("\t\t                  $('#' + id).append(\"<option value='\" + value.CD +\"'>\"+value.NM + \"</option>\");\r\n");
      out.write("\t\t               })\r\n");
      out.write("\t\t            })\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t\t         else{\r\n");
      out.write("\t\t            $('#' + id).find(\"option\").remove().end().append(\"<option value=>No Data</option>\");\r\n");
      out.write("\t\t            return;\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t         } else if(tagName == \"UL\"){\r\n");
      out.write("\t        \t if(jsonArrObj.length > 0){\r\n");
      out.write("\t\t            $('#' + id).find(\"li\").remove().end();\r\n");
      out.write("\t\t            $.each(jsonArrObj, function(index, item){\r\n");
      out.write("\t\t               $(item).each(function (key, value) {\r\n");
      out.write("\t\t                  $('#' + id).append(\"<li data-cd='\" + value.CD +\"'>\"+value.NM + \"</li>\");\r\n");
      out.write("\t\t               })\r\n");
      out.write("\t\t            })\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t\t         else{\r\n");
      out.write("\t\t            $('#' + id).find(\"li\").remove().end().append(\"<li data-cd=''>No Data</li>\");\r\n");
      out.write("\t\t            return;\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t         }\r\n");
      out.write("\t      },\r\n");
      out.write("\t      error:function(request, status, error){\r\n");
      out.write("\t         alert(error);\r\n");
      out.write("\t      }\r\n");
      out.write("\t   })\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction saveEditModal(){\r\n");
      out.write("\t\tvar userCD = \"\";\r\n");
      out.write("\t\tvar gumsu = '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tif(gumsu == \"\"){\r\n");
      out.write("\t\t\tuserCD = doact.userCd;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tuserCD = gumsu;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("    \tif(gumsu == \"\" && (doact.userCd == \"\" || doact.userCd == undefined)){\r\n");
      out.write("    \t\talert(\"로그인정보가 없습니다.\\r\\n다시 로그인하세요.\");\r\n");
      out.write("    \t\tlocation.href = \"/Page/Login\";\r\n");
      out.write("    \t\treturn;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("\t\t/* if(userCD == \"\"){\r\n");
      out.write("\t\t\talert(\"로그인정보가 없습니다.\\r\\n다시 로그인하세요.\");\r\n");
      out.write("\t\t\tlocation.href = \"/Page/Login\"\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar txtAera = $('#chagamResn').val().split('/');\r\n");
      out.write("\t\tvar chagamResn = [];\r\n");
      out.write("\t\tfor(var i=0;i<txtAera.length;i++){\r\n");
      out.write("\t\t\tif(txtAera[i] != ''){\r\n");
      out.write("\t\t\t\tchagamResn.push(txtAera[i]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar jpId = $('#junpyoId').val(); \r\n");
      out.write("\t    var keratype = $('#keraType').text(); \r\n");
      out.write("\t    var grade = $('#SltGrade').attr(\"data-cd\");//등급코드\r\n");
      out.write("\t    var gradeNm = $(\"#SltGrade\").val();//등급명\r\n");
      out.write("\t    var gumsubigo = $('#isptRmk').val();//검수비고\r\n");
      out.write("\t    var chagam = $('#lossWeight').val();//감량중량\r\n");
      out.write("\t    chagam = uncomma(chagam);\r\n");
      out.write("\t    var jState = chagamResn;\r\n");
      out.write("\t    \r\n");
      out.write("\t    /* if($('#lossCause').val() == 'writeResn'){\r\n");
      out.write("\t    \tjState = $('#inputResn').val();\r\n");
      out.write("\t    }else{\r\n");
      out.write("\t    \tjState = $('#lossCause').val();//감량사유\r\n");
      out.write("\t    } */\r\n");
      out.write("\t    \r\n");
      out.write("\t    if(jpId == null || jpId == ''){\r\n");
      out.write("\t    \talert('전표번호가 없습니다. 다시 로그인 하세요.');\r\n");
      out.write("\t    \treturn;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    /* else if(chagam > 0 && (jState == null || jState.length == 0)){\r\n");
      out.write("\t    \talert('감량사유를 선택하세요');\r\n");
      out.write("\t    \treturn;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else if(chagam == 0 && (jState != null || jState.length > 0)){\r\n");
      out.write("\t    \talert('감량중량을 입력하세요');\r\n");
      out.write("\t    \treturn;\r\n");
      out.write("\t    } */\r\n");
      out.write("\t    \r\n");
      out.write("\t    //2021-01-12주석처리\r\n");
      out.write("\t    /* if(grade == null || grade == '' || gradeNm == null || gradeNm == ''){\r\n");
      out.write("\t    \talert('등급을 선택하세요');\r\n");
      out.write("\t    \treturn;\r\n");
      out.write("\t    } */\r\n");
      out.write("\t   \r\n");
      out.write("\t   /*2023-01-30 등급 여러개 중 비율이 제일 높은거로 저장*/\r\n");
      out.write("\t   var MaxGradeCd = $(\"#info_user\").attr(\"data-grade\");\r\n");
      out.write("\t   var MaxGradeNm = $(\"#info_user\").attr(\"data-gradeNm\");\r\n");
      out.write("\t   \r\n");
      out.write("\t   //var MaxGradeCd = $(\"#SltGrade_inpt\").attr(\"data-cd\");\r\n");
      out.write("\t   //var MaxGradeNm = $(\"#SltGrade_inpt\").val();\r\n");
      out.write("\t   \r\n");
      out.write("\t    \r\n");
      out.write("\t    var data = {};\r\n");
      out.write("\t    \r\n");
      out.write("\t    data[\"junpyoId\"] = jpId; //전표 ID 추가!!!!\r\n");
      out.write("\t    /* data[\"carNo\"] = $('#carNum').val();\r\n");
      out.write("\t    data[\"weight\"] = $('#CstSbjt').val();\r\n");
      out.write("\t    data[\"compNm\"] = $('#CstStt').val(); */\r\n");
      out.write("\t    data[\"keraType\"] = keratype; \r\n");
      out.write("\t    \r\n");
      out.write("\t    if(MaxGradeCd == \"\"){\r\n");
      out.write("\t    \tif(grade == null || grade == '' || gradeNm == null || gradeNm == ''){\r\n");
      out.write("\t\t    \talert('등급을 선택하세요');\r\n");
      out.write("\t\t    \treturn;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tdata[\"j_Serial\"] = grade;//등급코드\r\n");
      out.write("\t\t    data[\"gubun1\"] = gradeNm;//등급명\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else{\r\n");
      out.write("\t    \tdata[\"j_Serial\"] = MaxGradeCd;//등급코드\r\n");
      out.write("\t\t    data[\"gubun1\"] = MaxGradeNm;//등급명\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    //data[\"j_state\"] = jState;//감량사유\r\n");
      out.write("\t    data[\"stateList\"] = jState;//감량사유\r\n");
      out.write("\t    \r\n");
      out.write("\t    data[\"gumsubigo\"] = gumsubigo;//검수비고\r\n");
      out.write("\t    data[\"chagam\"] = chagam;//감량중량\r\n");
      out.write("\t    data[\"insano\"] = userCD;\r\n");
      out.write("\t    \r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t       url: \"/Page/saveInspectionInfo.do\",\r\n");
      out.write("\t       type: \"POST\",\r\n");
      out.write("\t       dataType: \"json\",\r\n");
      out.write("\t       data: data,\r\n");
      out.write("\t       success: function(result){\r\n");
      out.write("\t          alert('저장이 완료되었습니다.');\r\n");
      out.write("\t          goPage();\r\n");
      out.write("\t       }\r\n");
      out.write("\t    })\r\n");
      out.write("\t }\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goPage(){\r\n");
      out.write("\t\tlocation.href = \"InspectionGrid\"\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getChagamReason(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"/Page/getChagamReason\",\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tdata = data.data;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t\t\t\t$('#dropCont').append('<li><label class=\"font_normal\"><input type=\"checkbox\" name=\"chkReason\" value=\"'+data[i]['REASON']+'\">'+data[i]['REASON']+'</label></li>');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction dropDown(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#dropCont').toggleClass('clickDropDown');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($('#dropCont').hasClass('clickDropDown')){\r\n");
      out.write("\t\t\t$('#dropdowntxt').text('선택');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#dropdowntxt').text('완료');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction chkReason(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($('#dropdowntxt').text() == '선택'){\r\n");
      out.write("\t\t\t$(\"input:checkbox[name='chkReason']:checked\").each(function() {\r\n");
      out.write("\t\t\t\tvar chkval = $(this).val();\r\n");
      out.write("\t\t\t\tvar chagamResnval = $('#chagamResn').val();\r\n");
      out.write("\t\t\t\t$('#chagamResn').val(chagamResnval + chkval + '/');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"input:checkbox[name='chkReason']\").prop(\"checked\", false);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#chagamResn').val('');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getSessionInfo(){\r\n");
      out.write("       \t$.ajax({\r\n");
      out.write("               url : \"/Page/getSessionInfo\",\r\n");
      out.write("               type : \"POST\",\r\n");
      out.write("               dataType : \"json\",\r\n");
      out.write("               data : \"\",\r\n");
      out.write("               async:false,\r\n");
      out.write("               success : function(data) {\r\n");
      out.write("                  doact.userCd = data[\"usrCd\"];\r\n");
      out.write("                  doact.userNm = data[\"usrNm\"];\r\n");
      out.write("               }\r\n");
      out.write("            })\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("$(document).on(\"click\",\".pro_sel_box\", function(){\r\n");
      out.write("\tvar width = $(this).css(\"width\");\r\n");
      out.write("\tvar droplist = $(this).next('ul.drop_selBox');\r\n");
      out.write("\tvar display = $(droplist).css(\"display\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(droplist).css(\"width\", width);\r\n");
      out.write("\t\r\n");
      out.write("\tif(display == \"none\"){\r\n");
      out.write("\t\t$(droplist).css(\"display\",\"block\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(droplist).css(\"display\",\"none\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).find('ul.drop_selBox').not(droplist).css(\"display\",\"none\");\r\n");
      out.write("})\t\r\n");
      out.write("\r\n");
      out.write("$(document).on(\"click\", \"ul.drop_selBox li\", function(){\r\n");
      out.write("\tvar val = $(this).attr(\"data-cd\");\r\n");
      out.write("\tvar name = $(this).text();\r\n");
      out.write("\tvar target = $(this).parent('ul.drop_selBox').prev('.pro_sel_box');\r\n");
      out.write("\t\r\n");
      out.write("\t$(target[0]).attr(\"data-cd\",val);\r\n");
      out.write("\t$(target[0]).val(name);\r\n");
      out.write("\t$(this).parent('ul.drop_selBox').css(\"display\",\"none\");\r\n");
      out.write("\t\r\n");
      out.write("\tif($(target).attr(\"id\") == \"SltDaeGrade_inpt\"){\r\n");
      out.write("\t\tsetBoundData(name,'SltGrade','title');\r\n");
      out.write("\t\t$(\"#SltGrade\").find(\"li\").remove();\r\n");
      out.write("\t\t$(\"#SltGrade_inpt\").val(\"\");\r\n");
      out.write("\t\t$(\"#sltItem\").find(\"li\").remove();\r\n");
      out.write("\t\t$(\"#sltItem_inpt\").val(\"\");\r\n");
      out.write("\t}else if($(target).attr(\"id\") == \"SltGrade_inpt\"){\r\n");
      out.write("\t\tsetBoundData(name, 'sltItem','l1');\r\n");
      out.write("\t\t$(\"#sltItem_inpt\").val(\"\");\r\n");
      out.write("\t}\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("/* $(document).on(\"input\",\"#SltDaeGrade_inpt\",function(){\r\n");
      out.write("\tvar title = $(this).val();\r\n");
      out.write("\tsetBoundData(title,'SltGrade','title');\r\n");
      out.write("})\r\n");
      out.write("\t\r\n");
      out.write("$(document).on(\"input\",'#SltGrade_inpt',function(){\r\n");
      out.write("     var gradeNm = $(this).val();\r\n");
      out.write("     setBoundData(gradeNm, 'sltItem','l1');\r\n");
      out.write("}); */\r\n");
      out.write("\t\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("///////JavaScript 데이터 바운드//////////\r\n");
      out.write("\tgetSessionInfo();\r\n");
      out.write("\tvar gumsu = '");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\tif(gumsu == \"\" && doact.userCd == \"\"){\r\n");
      out.write("\t\talert(\"로그인정보가 없습니다.\\r\\n다시 로그인하세요.\");\r\n");
      out.write("\t\tlocation.href = \"/Page/Login\"\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar user_name = '");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\tif(user_name == \"\"){\r\n");
      out.write("\t\t$(\"#info_user\").text(\"안녕하세요.\" + doact.userNm + \"님\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t$(\"#info_user\").text(\"안녕하세요.\" + user_name + \"님\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tsetBoundData('','SltDaeGrade','model');\r\n");
      out.write("\t\r\n");
      out.write("\tgetChagamReason();\r\n");
      out.write("\t\r\n");
      out.write("\t   $(\"#AddIsptRmk\").on(\"click\", function () { //검수내역 추가\r\n");
      out.write("\t      var gradeNm = $(\"#SltGrade_inpt\").val();\r\n");
      out.write("\t      \r\n");
      out.write("\t      if(gradeNm == \"\"){\r\n");
      out.write("\t    \t  alert(\"등급을 선택해주세요.\");\r\n");
      out.write("\t    \t  return;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      \r\n");
      out.write("\t      var itemNm = $(\"#sltItem_inpt\").val();\r\n");
      out.write("\t      var rate = $(\"#selectRate option:checked\").text();\r\n");
      out.write("\t      if(gradeNm == \"선택\"){\r\n");
      out.write("\t    \t  gradeNm = \"\";\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(itemNm == \"선택\"){\r\n");
      out.write("\t    \t  itemNm = \"\";\r\n");
      out.write("\t      }\r\n");
      out.write("\t      var input = \"\";\r\n");
      out.write("\t      var val = $(\"#isptRmk\").val();\r\n");
      out.write("\t      if(val.length == 0 || val == null){\r\n");
      out.write("\t    \t  if(itemNm == \"\"){\r\n");
      out.write("\t    \t\t  input = gradeNm + rate;\r\n");
      out.write("\t    \t  }\r\n");
      out.write("\t    \t  else{\r\n");
      out.write("\t    \t\t  input = gradeNm + rate + \",\" + itemNm;\r\n");
      out.write("\t    \t  }\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t    \t  $(\"#isptRmk\").val(input);\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t    \t  var gradeCd = $(\"#SltGrade_inpt\").attr(\"data-cd\");\r\n");
      out.write("    \t\t  $(\"#info_user\").attr(\"data-grade\", gradeCd);\r\n");
      out.write("    \t\t  $(\"#info_user\").attr(\"data-gradeNm\", gradeNm);\r\n");
      out.write("    \t\t  $(\"#info_user\").attr(\"data-rate\", rate);\r\n");
      out.write("    \t\t  \r\n");
      out.write("    \t\t  console.log(\"1:\"+gradeCd);\r\n");
      out.write("    \t\t  console.log(\"1:\"+gradeNm);\r\n");
      out.write("    \t\t  console.log(\"1:\"+rate);\r\n");
      out.write("\t      }\r\n");
      out.write("\t      else{\r\n");
      out.write("\t    \t  if(itemNm == \"\"){\r\n");
      out.write("\t    \t\t  input = gradeNm + rate;\r\n");
      out.write("\t    \t  }\r\n");
      out.write("\t    \t  else{\r\n");
      out.write("\t    \t\t  input = gradeNm + rate + \",\" + itemNm;\r\n");
      out.write("\t    \t  }\r\n");
      out.write("\t    \t  var prv_grade = $(\"#info_user\").attr(\"data-grade\");\r\n");
      out.write("\t    \t  var prv_rate = $(\"#info_user\").attr(\"data-rate\");\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t    \t  const parsedPrvRate = Number(prv_rate);\r\n");
      out.write("\t    \t  const parsedRate = Number(rate);\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t    \t  if(parsedRate > parsedPrvRate){\r\n");
      out.write("\t    \t\t  var gradeCd = $(\"#SltGrade_inpt\").attr(\"data-cd\");\r\n");
      out.write("\t    \t\t  $(\"#info_user\").attr(\"data-grade\", gradeCd);\r\n");
      out.write("\t    \t\t  $(\"#info_user\").attr(\"data-gradeNm\", $(\"#SltGrade_inpt\").val());\r\n");
      out.write("\t    \t\t  $(\"#info_user\").attr(\"data-rate\", parsedRate);\r\n");
      out.write("\t    \t  }\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t    \t  $(\"#isptRmk\").val(val + \";\" + input);\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t    \t  console.log(\"2:\"+gradeCd);\r\n");
      out.write("    \t\t  console.log(\"2:\"+$(\"#SltGrade_inpt\").val());\r\n");
      out.write("    \t\t  console.log(\"2:\"+parsedRate);\r\n");
      out.write("\t      }\r\n");
      out.write("\t      \r\n");
      out.write("\t   });\r\n");
      out.write("\t   \r\n");
      out.write("\t   $(\"#CancleIsptRmk\").on(\"click\", function () { //검수내역 취소\r\n");
      out.write("\t      $(\"#isptRmk\").val(\"\");\r\n");
      out.write("\t      $(\"#info_user\").attr(\"data-grade\", \"\");\r\n");
      out.write("\t      $(\"#info_user\").attr(\"data-gradeNm\", \"\");\r\n");
      out.write("\t      $(\"#info_user\").attr(\"data-rate\", \"0\");\r\n");
      out.write("\t   });\r\n");
      out.write("\t   \r\n");
      out.write("\t   $(\"#AddDtlItem\").on(\"click\", function () { //상세품목 추가\r\n");
      out.write("\t      var itemNm = $(\"#sltItem_inpt\").val();\r\n");
      out.write("\t      if(itemNm == \"선택\"){\r\n");
      out.write("\t    \t  itemNm = \"\";\r\n");
      out.write("\t      }\r\n");
      out.write("\t      var val = $(\"#isptRmk\").val();\r\n");
      out.write("\t      if(val.length == 0 || val == null){\r\n");
      out.write("\t    \t  $(\"#isptRmk\").val(itemNm);\r\n");
      out.write("\t      }\r\n");
      out.write("\t      else{\r\n");
      out.write("\t    \t  $(\"#isptRmk\").val(val + \";\" + itemNm);\r\n");
      out.write("\t      }\r\n");
      out.write("\t      \r\n");
      out.write("\t   });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//숫자콤마\r\n");
      out.write("function comma(str) {\r\n");
      out.write("        str = String(str);\r\n");
      out.write("        return str.replace(/(\\d)(?=(?:\\d{3})+(?!\\d))/g, '$1,');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//숫자콤마해제\r\n");
      out.write("function uncomma(str) {\r\n");
      out.write("    str = String(str);\r\n");
      out.write("    return str.replace(/[^\\d]+/g, '');\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("//숫자만사용+콤마\r\n");
      out.write("function inputNumberFormat(obj) {\r\n");
      out.write("    obj.value = comma(uncomma(obj.value));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//숫자만사용+콤마x\r\n");
      out.write("function inputOnlyNumberFormat(obj) {\r\n");
      out.write("    obj.value = onlynumber(uncomma(obj.value));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//숫자만사용\r\n");
      out.write("function onlynumber(str) {\r\n");
      out.write("    str = String(str);\r\n");
      out.write("    return str.replace(/(\\d)(?=(?:\\d{3})+(?!\\d))/g,'$1');\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    \tth{\r\n");
      out.write("    \t\ttext-align: center;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \ttd{\r\n");
      out.write("    \t\tpadding: 1%;\r\n");
      out.write("    \t\theight: 45px;\r\n");
      out.write("    \t\tmin-height: 45px;\r\n");
      out.write("    \t\tposition: relative;\r\n");
      out.write("    \t}\r\n");
      out.write("    </style>\r\n");
      out.write("<body style=\"background-color: black; color: white; \">\r\n");
      out.write("<div style=\"width: 95%;margin: auto; margin-top: 15px;height: 95%;\">\r\n");
      out.write("   <div style='float:right;margin-bottom: 5px;'>\r\n");
      out.write("      <p style=\"display:inline-block;\" id=\"info_user\" data-grade=\"\" data-gradeNm=\"\" data-rate=\"0\">안녕하세요. ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.usrnm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님</p>\r\n");
      out.write("      <button type='button' class='btn btn-default' onClick='location.href=\"/Page/Logout\"' >로그아웃</button>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div style=\"height: 100%;\">\r\n");
      out.write("      <table id=\"tbInfo\" border=\"1\" style=\"height: 100%; width: 100%; border-collapse: collapse; text-align: center; table-layout: fixed;\">\r\n");
      out.write("         <tr>\r\n");
      out.write("         \t<th>업체명</th>\r\n");
      out.write("         \t<td colspan=\"5\" style=\"text-align: left\"> \r\n");
      out.write("         \t\t<label id = \"company\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.dealer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("         \t</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>   \r\n");
      out.write("            <th>\r\n");
      out.write("               <label>차　번</label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td>\r\n");
      out.write("               <label id =\"carNum\" name= \"carNum\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("            </td>\r\n");
      out.write("            <th>\r\n");
      out.write("               <label>중　량</label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td>\r\n");
      out.write("            \r\n");
      out.write("               <label id = \"weight\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.weight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("            </td>\r\n");
      out.write("            <th>구　분</th>\r\n");
      out.write("         \t<td>\r\n");
      out.write("         \t\t<label id = \"keraType\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.deal_gb }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("         \t</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"6\" style=\"background-color: yellow;color: black; font-weight: bold\">\r\n");
      out.write("               <span class=\"\">등급정보 입력<i class=\"fa fa-lock\"></i></span>\r\n");
      out.write("           \t</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("         \t<th>대분류</th>\r\n");
      out.write("         \t<td colspan=\"5\" style=\"\"> \r\n");
      out.write("         \t\t<input class=\"pro_sel_box\" type=\"text\" readonly=\"readonly\" id=\"SltDaeGrade_inpt\">\r\n");
      out.write("         \t\t<ul class=\"drop_selBox\" id=\"SltDaeGrade\">\r\n");
      out.write("         \t\t</ul>\r\n");
      out.write("         \t\t<!-- <select id=\"SltDaeGrade\" style=\"height: 30px; width: 98%; color: black;\"></select> -->\r\n");
      out.write("         \t</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>\r\n");
      out.write("               <label>등　급</label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("               <!-- <select id=\"SltGrade\" style=\"height: 30px; width: 95%; color: black;\"></select> -->\r\n");
      out.write("               <input class=\"pro_sel_box\" type=\"text\" readonly=\"readonly\" id=\"SltGrade_inpt\">\r\n");
      out.write("         \t\t<ul class=\"drop_selBox\" id=\"SltGrade\">\r\n");
      out.write("         \t\t</ul>\r\n");
      out.write("            </td>\r\n");
      out.write("            <th>\r\n");
      out.write("               <label>비율선택</label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("               <select id=\"selectRate\" style=\"height: 30px; width: 95%; color: black;\">\r\n");
      out.write("                  <option value=\"1\">1</option>\r\n");
      out.write("                  <option value=\"2\">2</option>\r\n");
      out.write("                  <option value=\"3\">3</option>\r\n");
      out.write("                  <option value=\"4\">4</option>\r\n");
      out.write("                  <option value=\"5\">5</option>\r\n");
      out.write("                  <option value=\"6\">6</option>\r\n");
      out.write("                  <option value=\"7\">7</option>\r\n");
      out.write("                  <option value=\"8\">8</option>\r\n");
      out.write("                  <option value=\"9\">9</option>\r\n");
      out.write("               </select>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>\r\n");
      out.write("               <label>품　목</label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td colspan=\"3\">\r\n");
      out.write("               <!-- <select id=\"sltItem\" style=\"height: 30px;  width: 96.4%; color: black;\"></select> -->\r\n");
      out.write("               <input class=\"pro_sel_box\" type=\"text\" readonly=\"readonly\" id=\"sltItem_inpt\">\r\n");
      out.write("         \t\t<ul class=\"drop_selBox\" id=\"sltItem\">\r\n");
      out.write("         \t\t</ul>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("               <input type=\"button\" id=\"AddDtlItem\" value=\"상세품목추가\" class='btn btn-default'>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>      \r\n");
      out.write("         <tr>\r\n");
      out.write("            <th rowspan=\"2\">\r\n");
      out.write("               <label>검수비고</label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td colspan=\"5\">\r\n");
      out.write("               <input type=\"text\" id=\"isptRmk\" style=\"height: 30px; width: 98%; color: black;\">\r\n");
      out.write("            </td>   \r\n");
      out.write("         </tr>   \r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"5\">\r\n");
      out.write("               <input type=\"button\" id=\"AddIsptRmk\" value=\"검수내역추가\" class='btn btn-default'>\r\n");
      out.write("               <input type=\"button\" id=\"CancleIsptRmk\" value=\"검수내역취소\" class='btn btn-default'>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>   \r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>\r\n");
      out.write("               <label>감량중량</label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td colspan=\"5\">\r\n");
      out.write("               <input type=\"text\" id=\"lossWeight\" style=\"height: 30px; width: 98%; color: black;\" onkeyup=\"inputNumberFormat(this);\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>      \r\n");
      out.write("         <tr>\r\n");
      out.write("            <th rowspan=\"2\">\r\n");
      out.write("               <label>감량사유</label>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td colspan=\"5\" style=\"height: 50px;\">\r\n");
      out.write("               <div class=\"dropdown\" onclick=\"dropDown();chkReason();\"><label class=\"font_normal\" id=\"dropdowntxt\" style=\"margin-top: 10px;width: 98%;\">선택</label></div>\r\n");
      out.write("               <div class=\"dropdown-content clickDropDown\" id=\"dropCont\" style=\"margin-left: 1%;\">\r\n");
      out.write("\t\t       </div>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("         \t<td colspan=\"5\"><textarea id=\"chagamResn\" rows=\"3\" cols=\"\" style=\"width:98%;color: black;margin-top: 10px;margin-bottom: 10px;\"></textarea></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("      </table>   \r\n");
      out.write("      <div style=\"float: right; margin-top: 10px; margin-bottom: 5px\">\r\n");
      out.write("         <input type=\"hidden\" id=\"junpyoId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.junpyoid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("         <input type=\"button\" id=\"btnConfirm\" value=\"검수완료\" class='btn btn-default' onclick=\"saveEditModal();\">\r\n");
      out.write("      </div>\r\n");
      out.write("   </div> \r\n");
      out.write("   </div>     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/Page/Inspection.jsp(163,15) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.insano}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/Page/Inspection.jsp(382,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.insano}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/Page/Inspection.jsp(388,18) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.usrnm}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }
}
