/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2026-08-10 03:12:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1660696354000L));
    _jspx_dependants.put("jar:file:/daejist7/tomcat/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html style=\"height: 100%\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>로그인</title>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\" media=\"screen\" title=\"no title\" charset=\"utf-8\">\r\n");
      out.write("    <script src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/popper.min.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <!-- <script src=\"js/bootstrap.min.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<script>   \r\n");
      out.write("\tfunction setDateData(){\r\n");
      out.write("        var date = new Date(); \r\n");
      out.write("        var year = date.getFullYear(); \r\n");
      out.write("        var month = new String(date.getMonth()+1); \r\n");
      out.write("        var day = new String(date.getDate()); \r\n");
      out.write("\r\n");
      out.write("        // 한자리수일 경우 0을 채워준다. \r\n");
      out.write("        if(month.length == 1){ \r\n");
      out.write("          month = \"0\" + month; \r\n");
      out.write("        } \r\n");
      out.write("        if(day.length == 1){ \r\n");
      out.write("          day = \"0\" + day; \r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        return year + \"-\" + month + \"-\" + day;\r\n");
      out.write("   }\r\n");
      out.write("\t\r\n");
      out.write("\tfunction login(){\r\n");
      out.write("\t\tvar id = $(\"#usrid\").val();\r\n");
      out.write("\t\tvar pw = $(\"#passwd\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(id == \"\" || (id ==\"\" && pw != \"\")){\r\n");
      out.write("\t\t\talert(\"ID를 입력해주세요.\");\r\n");
      out.write("\t\t\t$(\"#usrid\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else if(id != \"\" && pw ==\"\"){\r\n");
      out.write("\t\t\talert(\"PW를 입력해주세요.\");\r\n");
      out.write("\t\t\t$(\"#passwd\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.form1.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(e) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t/* $('#login-submit').on('click',function(){\r\n");
      out.write("\t\t\tvar id = $(\"#usrid\").val();\r\n");
      out.write("\t\t\tvar pw = $(\"#passwd\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(id == \"\" || (id ==\"\" && pw != \"\")){\r\n");
      out.write("\t\t\t\talert(\"ID를 입력해주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#usrid\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}else if(id != \"\" && pw ==\"\"){\r\n");
      out.write("\t\t\t\talert(\"PW를 입력해주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#passwd\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tconsole.log(\"리턴안되냐\");\r\n");
      out.write("\t\t\tdocument.form1.submit();\r\n");
      out.write("\t\t}); */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#usrid').keyup(function(event){\r\n");
      out.write("\t\t\t  if(event.keyCode == '13'){\r\n");
      out.write("\t\t\t\t  $(\"#passwd\").focus();\r\n");
      out.write("\t\t\t  } \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#passwd').keyup(function(event){\r\n");
      out.write("\t\t\t  if(event.keyCode == '13'){\r\n");
      out.write("\t\t\t\t  login();\r\n");
      out.write("\t\t\t  } \r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body style=\"background-color: black;height: 100%\">\r\n");
      out.write("<div style=\"width: 100%;height: 100%;position: relative;\">\r\n");
      out.write("    <div class=\"login-box well\" style=\"width: 300px;height: 220px;position: absolute;left: 50%;top: 50%;margin-left: -150px;margin-top: -110px;\">\r\n");
      out.write("        <form accept-charset=\"UTF-8\" role=\"form\" method=\"POST\" action=\"LoginCheck\" id=\"check\" name=\"form1\">\r\n");
      out.write("            <legend>대지검수프로그램</legend>\r\n");
      out.write("             <div class=\"input-group\">\r\n");
      out.write("                 <span class=\"input-group-addon\"><i class=\"fa fa-user\"></i></span>\r\n");
      out.write("                 \t<input type=\"text\" id=\"usrid\" name = \"usrid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.usrid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"ID를 입력하세요\" class=\"form-control\" />\r\n");
      out.write("             </div>\r\n");
      out.write("             <div class=\"input-group\">\r\n");
      out.write("                 <span class=\"input-group-addon\"><i class=\"fa fa-lock\"></i></span>\r\n");
      out.write("                 <input type=\"password\" id=\"passwd\" name = \"passwd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.passwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"비밀번호를 입력하세요\" class=\"form-control\" />\r\n");
      out.write("             </div>\r\n");
      out.write(" \t\t\t\t<input type=\"hidden\" id=\"j_date\" name=\"j_date\" value=\"\">\r\n");
      out.write("            <button type=\"button\" id=\"login-submit\" class=\"btn btn-default btn-block\" onclick=\"login();\">로그인</button>\r\n");
      out.write("            <input type=\"checkbox\" name=\"chkbox\" checked=\"checked\"><label>아이디저장</label>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
