/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2026-08-14 08:13:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inoutCome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1786324918000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"user-scalable=yes, width=device-width\">\r\n");
      out.write("        <meta id=\"_csrf\" name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        <meta id=\"_csrf_name\" name=\"_csrf_name\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        <title>대지에스텍</title>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"icon\" href=\"/daejiM/resources/common/img/logo.ico\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/daejiM/resources/common/css/reset.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/daejiM/resources/common/css/header.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/daejiM/resources/common/css/layout.css\">\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@10\"></script>\r\n");
      out.write("        <script src=\"/daejiM/resources/common/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- 페이징 -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://uicdn.toast.com/tui.pagination/latest/tui-pagination.css\">\r\n");
      out.write("        <script src=\"https://uicdn.toast.com/tui.pagination/latest/tui-pagination.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/daejiM/resources/common/css/common.css\">\r\n");
      out.write("        <script src=\"/daejiM/resources/common/js/commom.js?v=2\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div id=\"lodingView\">\r\n");
      out.write("            <div class=\"loading-container\">\r\n");
      out.write("                <div class=\"loading\"></div>\r\n");
      out.write("                <div id=\"loading-text\">loading</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- End of header -->");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/daejiM/resources/view/css/inoutCome.css\" />\r\n");
      out.write("<script src=\"/daejiM/resources/view/js/inoutCome/inoutCome.js?v=");
      out.print(System.currentTimeMillis());
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <div class=\"prev\" onclick=\"location.href='/daejiM/main'\"><svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                        viewBox=\"0 0 24 24\" width=\"24\" height=\"24\">\r\n");
      out.write("                        <path fill=\"none\" d=\"M0 0H24V24H0z\" />\r\n");
      out.write("                        <path\r\n");
      out.write("                            d=\"M14 4.5V9c5.523 0 10 4.477 10 10 0 .273-.01.543-.032.81-1.463-2.774-4.33-4.691-7.655-4.805L16 15h-2v4.5L6 12l8-7.5zm-6 0v2.737L2.92 12l5.079 4.761L8 19.5 0 12l8-7.5z\"\r\n");
      out.write("                            fill=\"rgba(255,255,255,1)\" />\r\n");
      out.write("                    </svg></div>\r\n");
      out.write("                <h4>대지에스텍</h4>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img src=\"/daejiM/resources/common/img/logo_W.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <main id=\"mainWrap\">\r\n");
      out.write("            <div id=\"contentView\">\r\n");
      out.write("                <div class=\"list_title search\">\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <div class=\"closure m_closure\">\r\n");
      out.write("                            <input type=\"date\" id=\"fdate\" min=\"0000-01-01\" max=\"9999-12-31\"><span class=\"hide\">~</span><input type=\"date\" id=\"tdate\" min=\"0000-01-01\" max=\"9999-12-31\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"closure\">\r\n");
      out.write("                            <label><input type=\"radio\" id=\"inCome\" name=\"closure\" value=\"매입\" checked> <span > 매입</span></label>\r\n");
      out.write("                            <label><input type=\"radio\" id=\"outCome\" name=\"closure\" value=\"매출\"> <span > 매출</span></label>\r\n");
      out.write("                            <label><input type=\"radio\" id=\"direct\" name=\"closure\" value=\"직송\"> <span > 직송</span></label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"closure\">\r\n");
      out.write("                            <label><input type=\"checkbox\" name=\"chkDaegb\" value=\"고철A\" checked=\"checked\"> <span> 고철A</span></label>\r\n");
      out.write("                            <label><input type=\"checkbox\" name=\"chkDaegb\" value=\"고철B\" checked=\"checked\"> <span> 고철B</span></label>\r\n");
      out.write("                            <label><input type=\"checkbox\" name=\"chkDaegb\" value=\"슈레더\" checked=\"checked\"> <span> 슈레더</span></label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"button\" id=\"BtnRetr\">조회</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"tab_menu\">\r\n");
      out.write("                    <ul class=\"tab_wrap\">\r\n");
      out.write("                        <li class=\"tab1 on\">거래처별</li>\r\n");
      out.write("                        <li class=\"tab2\">등급별</li>\r\n");
      out.write("                        <li class=\"tab3\">업체별 현황</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <!--매입-->\r\n");
      out.write("                <div class=\"list_table inCome\">\r\n");
      out.write("                    <!--매입 / 거래처-->\r\n");
      out.write("                    <div class=\"list_table_in inCome_client client\">\r\n");
      out.write("                        <table class=\"jb-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <!-- <th style=\"max-width:50px; min-width:50px;\">-</th> -->\r\n");
      out.write("                                    <th colspan=\"21\">마감정보</th>\r\n");
      out.write("                                    <th>부대비용</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"tableCol\">\r\n");
      out.write("                                    <!-- <th style=\"max-width:50px; min-width:50px;\"></th> -->\r\n");
      out.write("                                    <th class=\"shop_name\">상호</th>\r\n");
      out.write("                                    <th>마감일자</th>\r\n");
      out.write("                                    <th>계근일자</th>\r\n");
      out.write("                                    <th>담당자</th>\r\n");
      out.write("                                    <th>차량</th>\r\n");
      out.write("                                    <th>대지중량</th>\r\n");
      out.write("                                    <th>감량</th>\r\n");
      out.write("                                    <th>인수량</th>\r\n");
      out.write("                                    <th>중량차이</th>\r\n");
      out.write("                                    <th>등급</th>\r\n");
      out.write("                                    <th>기준단가</th>\r\n");
      out.write("                                    <th>지급단가</th>\r\n");
      out.write("                                    <th>차액</th>\r\n");
      out.write("                                    <th>도착도단가</th>\r\n");
      out.write("                                    <th>운반비</th>\r\n");
      out.write("                                    <th>운반비단가</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>도착도금액</th>\r\n");
      out.write("                                    <th>감량사유</th>\r\n");
      out.write("                                    <th>사진</th>\r\n");
      out.write("                                    <th>비고</th>\r\n");
      out.write("                                    <th>부대비용</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--매입 / 등급별-->\r\n");
      out.write("                    <div class=\"list_table_in inCome_level level\">\r\n");
      out.write("                        <table class=\"jb-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr class=\"tableCol\">\r\n");
      out.write("                                    <th class=\"shop_name\">등급</th>\r\n");
      out.write("                                    <th>인수량</th>\r\n");
      out.write("                                    <th>대지중량</th>\r\n");
      out.write("                                    <th>차이중량(KG)</th>\r\n");
      out.write("                                    <th>기준단가</th>\r\n");
      out.write("                                    <th>지급단가</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>감량</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--매입 / 업체별-->\r\n");
      out.write("                    <div class=\"list_table_in inCome_company company\">\r\n");
      out.write("                        <table class=\"jb-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr class=\"tableCol\">\r\n");
      out.write("                                    <th class=\"shop_name\">거래처</th>\r\n");
      out.write("                                    <th>담당자</th>\r\n");
      out.write("                                    <th>인수량</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>평균단가</th>\r\n");
      out.write("                                    <th>지역</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                                \r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!--매출-->\r\n");
      out.write("                <div class=\"list_table outCome\">\r\n");
      out.write("                    <!-- <div class=\"tab_menu\">\r\n");
      out.write("                        <ul class=\"tab_wrap\">\r\n");
      out.write("                            <li class=\"tab1 on\">거래처별</li>\r\n");
      out.write("                            <li class=\"tab2\">등급별</li>\r\n");
      out.write("                            <li class=\"tab3\">업체별 현황</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("                    <!--매출 / 거래처-->\r\n");
      out.write("                    <div class=\"list_table_in outCome_client client\">\r\n");
      out.write("                        <table class=\"jb-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <!-- <th style=\"max-width:50px; min-width:50px;\">-</th> -->\r\n");
      out.write("                                    <th colspan=\"21\">마감정보</th>\r\n");
      out.write("                                    <th colspan=\"3\">기타비용1</th>\r\n");
      out.write("                                    <th colspan=\"3\">기타비용2</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"tableCol\">\r\n");
      out.write("                                    <!-- <th style=\"max-width:50px; min-width:50px;\"></th> -->\r\n");
      out.write("                                    <th class=\"shop_name\">상호</th>\r\n");
      out.write("                                    <th>마감일자</th>\r\n");
      out.write("                                    <th>계근일자</th>\r\n");
      out.write("                                    <th>담당자</th>\r\n");
      out.write("                                    <th>차량</th>\r\n");
      out.write("                                    <th>대지중량</th>\r\n");
      out.write("                                    <th>감량</th>\r\n");
      out.write("                                    <th>인수량</th>\r\n");
      out.write("                                    <th>중량차이</th>\r\n");
      out.write("                                    <th>등급</th>\r\n");
      out.write("                                    <th>기준단가</th>\r\n");
      out.write("                                    <th>지급단가</th>\r\n");
      out.write("                                    <th>차액</th>\r\n");
      out.write("                                    <th>도착도단가</th>\r\n");
      out.write("                                    <th>운반비</th>\r\n");
      out.write("                                    <th>운반비단가</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>도착도금액</th>\r\n");
      out.write("                                    <th>감량사유</th>\r\n");
      out.write("                                    <th>사진</th>\r\n");
      out.write("                                    <th>비고</th>\r\n");
      out.write("                                    <th>업체명</th>\r\n");
      out.write("                                    <th>내용</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>업체명</th>\r\n");
      out.write("                                    <th>내용</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                                \r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--매출 / 등급별-->\r\n");
      out.write("                    <div class=\"list_table_in outCome_level level\">\r\n");
      out.write("                        <table class=\"jb-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr class=\"tableCol\">\r\n");
      out.write("                                    <th class=\"shop_name\">등급</th>\r\n");
      out.write("                                    <th>인수량</th>\r\n");
      out.write("                                    <th>대지중량</th>\r\n");
      out.write("                                    <th>차이중량(KG)</th>\r\n");
      out.write("                                    <th>기준단가</th>\r\n");
      out.write("                                    <th>매출단가</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>감량</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                                \r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--매출 / 업체별-->\r\n");
      out.write("                    <div class=\"list_table_in outCome_company company\">\r\n");
      out.write("                        <table class=\"jb-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr class=\"tableCol\">\r\n");
      out.write("                                    <th class=\"shop_name\">거래처</th>\r\n");
      out.write("                                    <th>담당자</th>\r\n");
      out.write("                                    <th>인수량</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>평균단가</th>\r\n");
      out.write("                                    <th>지역</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                                \r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!--직송-->\r\n");
      out.write("                <div class=\"list_table direct\">\r\n");
      out.write("                    <!-- <div class=\"tab_menu\">\r\n");
      out.write("                        <ul class=\"tab_wrap\">\r\n");
      out.write("                            <li class=\"tab1 on\">거래처별</li>\r\n");
      out.write("                            <li class=\"tab2\">등급별</li>\r\n");
      out.write("                            <li class=\"tab3 choice_pop\">업체별 현황</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("                    <!--직송 / 거래처-->\r\n");
      out.write("                    <div class=\"list_table_in direct_client client\">\r\n");
      out.write("                        <table class=\"jb-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <!-- <th style=\"max-width:50px; min-width:50px;\">-</th> -->\r\n");
      out.write("                                    <th colspan=\"17\">마감정보</th>\r\n");
      out.write("                                    <th colspan=\"3\">기타비용1</th>\r\n");
      out.write("                                    <th colspan=\"3\">기타비용2</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"tableCol\">\r\n");
      out.write("                                    <!-- <th style=\"max-width:50px; min-width:50px;\">출</th> -->\r\n");
      out.write("                                    <th class=\"shop_name\">매출처</th>\r\n");
      out.write("                                    <th>마감일자</th>\r\n");
      out.write("                                    <th>담당자</th>\r\n");
      out.write("                                    <th>등급</th>\r\n");
      out.write("                                    <th>차량</th>\r\n");
      out.write("                                    <th>매출중량</th>\r\n");
      out.write("                                    <th>매출단가</th>\r\n");
      out.write("                                    <th>매출액</th>\r\n");
      out.write("                                    <th>매입처</th>\r\n");
      out.write("                                    <th>매입단가</th>\r\n");
      out.write("                                    <th>도착도단가</th>\r\n");
      out.write("                                    <th>매입금액</th>\r\n");
      out.write("                                    <th>차액</th>\r\n");
      out.write("                                    <th>운반비</th>\r\n");
      out.write("                                    <th>운반비단가</th>\r\n");
      out.write("                                    <th>도착도금액</th>\r\n");
      out.write("                                    <th>감량</th>\r\n");
      out.write("                                    <th>업체명</th>\r\n");
      out.write("                                    <th>내용</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>업체명</th>\r\n");
      out.write("                                    <th>내용</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                                \r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--직송 / 등급별-->\r\n");
      out.write("                    <div class=\"list_table_in direct_level level\">\r\n");
      out.write("                        <table class=\"jb-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr class=\"tableCol\">\r\n");
      out.write("                                    <th class=\"shop_name\">등급</th>\r\n");
      out.write("                                    <th>인수량</th>\r\n");
      out.write("                                    <th>대지중량</th>\r\n");
      out.write("                                    <th>차이중량(KG)</th>\r\n");
      out.write("                                    <th>기준단가</th>\r\n");
      out.write("                                    <th>지급단가</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>감량</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>경량 AA</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>20,220,301</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>20,220,301</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>-100</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>640.0</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>543.0</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>234,513,700</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>543.0</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                                \r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--직송 / 업체별-->\r\n");
      out.write("                    <div class=\"list_table_in direct_company company\">\r\n");
      out.write("                        <table class=\"jb-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr class=\"tableCol\">\r\n");
      out.write("                                    <th class=\"shop_name\">거래처</th>\r\n");
      out.write("                                    <th>담당자</th>\r\n");
      out.write("                                    <th>인수량</th>\r\n");
      out.write("                                    <th>금액</th>\r\n");
      out.write("                                    <th>평균단가</th>\r\n");
      out.write("                                    <th>지역</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>25시자원 (홍길동)(김해)</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>홍길동</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>123,230</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>123,123</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>234.5</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <p>김해</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                                \r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"pagination\" class=\"tui-pagination\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <div id=\"pop_add\">\r\n");
      out.write("                    <div class=\"popText\">\r\n");
      out.write("                        <h5>계근사진 조회</h5>\r\n");
      out.write("                        <div class=\"list_box\">\r\n");
      out.write("                            <div class=\"list\">\r\n");
      out.write("                                <p>1차 계근</p>\r\n");
      out.write("                                <div class=\"img_box\">\r\n");
      out.write("                                    <p><img id=\"img1_1\" src=\"/daejiM/resources/common/img/no_image.jpg\"></p>\r\n");
      out.write("                                    <p><img id=\"img1_2\" src=\"/daejiM/resources/common/img/no_image.jpg\"></p>\r\n");
      out.write("                                    <p><img id=\"img1_3\" src=\"/daejiM/resources/common/img/no_image.jpg\"></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"list\">\r\n");
      out.write("\r\n");
      out.write("                                <p>2차 계근</p>\r\n");
      out.write("                                <div class=\"img_box\">\r\n");
      out.write("                                    <p><img id=\"img2_1\" src=\"/daejiM/resources/common/img/no_image.jpg\"></p>\r\n");
      out.write("                                    <p><img id=\"img2_2\" src=\"/daejiM/resources/common/img/no_image.jpg\"></p>\r\n");
      out.write("                                    <p><img id=\"img2_3\" src=\"/daejiM/resources/common/img/no_image.jpg\"></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"pop_btn\">\r\n");
      out.write("                            <button class=\"pop_close\" id=\"imgClose\">닫기</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"jkgub\">\r\n");
      out.write("                <div id=\"pop_choice\">\r\n");
      out.write("                    <div class=\"popText\">\r\n");
      out.write("                        <h6>매입출 선택</h6>\r\n");
      out.write("                        <div class=\"list_box\">\r\n");
      out.write("                            <p>매입/매출 현황 중</p>\r\n");
      out.write("                            <p>하나를 선택하세요</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pop_btn\" id=\"pop_choice_btn_box\">\r\n");
      out.write("                            <button type=\"button\">매입</button>\r\n");
      out.write("                            <button type=\"button\">매출</button>\r\n");
      out.write("                            <button class=\"pop_close\" id=\"choiceClose\">닫기</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- #contentView -->\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
