/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2026-08-14 08:13:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1786324918000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("        \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"user-scalable=yes, width=device-width\">\r\n");
      out.write("        <meta id=\"_csrf\" name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        <meta id=\"_csrf_name\" name=\"_csrf_name\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        <title>대지에스텍</title>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"icon\" href=\"/daejiM/resources/common/img/logo.ico\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/daejiM/resources/common/css/reset.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/daejiM/resources/common/css/header.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/daejiM/resources/common/css/layout.css\">\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@10\"></script>\r\n");
      out.write("        <script src=\"/daejiM/resources/common/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- 페이징 -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://uicdn.toast.com/tui.pagination/latest/tui-pagination.css\">\r\n");
      out.write("        <script src=\"https://uicdn.toast.com/tui.pagination/latest/tui-pagination.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/daejiM/resources/common/css/common.css\">\r\n");
      out.write("        <script src=\"/daejiM/resources/common/js/commom.js?v=2\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div id=\"lodingView\">\r\n");
      out.write("            <div class=\"loading-container\">\r\n");
      out.write("                <div class=\"loading\"></div>\r\n");
      out.write("                <div id=\"loading-text\">loading</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- End of header -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/daejiM/resources/view/css/login.css\" />\r\n");
      out.write("        <script src=\"/daejiM/resources/view/js/login/login.js?v=");
      out.print(System.currentTimeMillis());
      out.write("\" defer></script>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"wrap\">\r\n");
      out.write("            <main id=\"mainWrap\">\r\n");
      out.write("                <svg id=\"logoBackground\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 110.11 75.65\">\r\n");
      out.write("                    <defs>\r\n");
      out.write("                        <style>\r\n");
      out.write("                            .cls-1 { fill: #fff; }\r\n");
      out.write("                            .cls-2 { fill: #07549b; }\r\n");
      out.write("                            .cls-3 { fill: url(#logoGradient); }\r\n");
      out.write("                            .cls-4 { fill: none; }\r\n");
      out.write("                            .cls-5 { fill: #00605d; }\r\n");
      out.write("                        </style>\r\n");
      out.write("\r\n");
      out.write("                        <linearGradient id=\"logoGradient\" x1=\"0\" y1=\"42.34\" x2=\"110.11\" y2=\"42.34\" gradientUnits=\"userSpaceOnUse\">\r\n");
      out.write("                            <stop offset=\"0\" stop-color=\"#b0d6e1\" />\r\n");
      out.write("                            <stop offset=\".22\" stop-color=\"#689bbb\" />\r\n");
      out.write("                            <stop offset=\".46\" stop-color=\"#4279a8\" />\r\n");
      out.write("                            <stop offset=\"1\" stop-color=\"#0b4488\" />\r\n");
      out.write("                        </linearGradient>\r\n");
      out.write("                    </defs>\r\n");
      out.write("\r\n");
      out.write("                    <g>\r\n");
      out.write("                        <path class=\"cls-3\" d=\"M28.62,9.79c9.4-1.37,20.67-.73,28.84,.71-8.15-1.21-18.9-2.24-29.32,.21-5.46,1.24-13.05,3.76-17.88,10.59-3.15,4.18-2.7,10.32-1.39,14.08,1.43,4.08,3.05,6.5,6.29,10,4.1,4.27,9.02,7.64,10.73,8.68,4,2.56,9.82,5.23,14.61,6.78,5.02,1.83,10.95,3.44,15.76,3.85,2.8,.29,10.66,1.17,17.3,.74,5.29-.39,11.78-1.76,16.56-3.66,8.46-3.35,14.35-10.53,12.78-19.33-1.12-6.24-4.59-10.08-7.65-13.48-2.26-2.28-5.36-4.81-8.12-6.73-5.38-3.74-13.96-7.13-18.58-9.09,8.95,3.15,17.68,7.22,24.91,12.47,2.72,1.92,10.28,8.72,12.12,11.82s3.87,6.43,4.34,10.44c.57,4.91-.33,8.45-1.46,10.76-1.64,3.33-3.79,5.4-6.44,7.61-2.64,2.25-5.76,3.79-9.07,5.27-6.69,2.81-14.13,3.76-18.92,4.05-6.37,.28-14.34-.39-18.45-.93-5.82-.68-12.9-2.49-18.59-4.69-5.89-2.38-11.62-5.2-16.26-8.14-2.29-1.65-9.47-6.79-13.04-11.17-3.34-4.1-6.52-8.86-7.54-14.84-.43-4.47,.06-7.2,1.22-10.01,1.12-2.82,4.04-6.21,6.07-7.83,4.09-3.24,12.17-7.14,21.18-8.19Z\" />\r\n");
      out.write("                        <path class=\"cls-4\" d=\"M56,38.32c2.03-.95,1.32-1.28,2.45-2.5,2.82-3.05,3.76-7.35,3.81-10.93v-.02s0-.56,0-.56v-.23c-.05-3.78-.48-8.07-3.29-11.12-2.01-2.18-5.97-4.79-10.95-4.79h-12.42V40.81h10.53c-.1-.61-.09-3.85-.09-4.56v-11.62h8.72\" />\r\n");
      out.write("                        <path class=\"cls-5\" d=\"M46.12,40.81h-9.73V7.98h11.62c5.75,0,9.01,2.72,11.02,4.9,2.82,3.05,3.17,7.43,3.22,11.21v.23s0,.56,0,.56v.02c0,3.98-1,7.48-2.66,9.72-.71,.88-1.93,2.76-3.6,3.71,.64,1.7,2.4,3.34,8.84,3.57,.11-.11,.23-.23,.34-.34,4.41-4.78,5.88-11.22,5.84-17,.12-5.87-1.57-13.11-5.98-17.89-3.11-3.37-9.18-6.66-17.02-6.66H20.16V7.98h7.44V40.81h-7.24v8.18h27.65c2.33,0,5.93-1.09,7.82-1.68-4.15-1.14-9.07-2.39-9.71-6.5Z\" />\r\n");
      out.write("                        <path class=\"cls-2\" d=\"M54.76,24.63h-8.72v11.62c0,.7-.01,3.94-.01,4.56h1.99c2.07,.55,6.4-.13,7.98-2.49-.12-.16-.92-.98-1.12-2.92-.2-1.94-.12-10.77-.12-10.77Z\" />\r\n");
      out.write("                        <path class=\"cls-2\" d=\"M70.31,.18V7.82h10.5v25.47c0,3.27-.58,8.94-8.49,8.94-4.36,0-6.19-.24-7.49-.34-2.18,2.28-4.72,4.09-9,5.42,4.62,1.27,9.42,2.18,16.49,2.18,13.84,0,16.83-7.94,16.83-16.2V7.82h11.54V.18h-30.39Z\" />\r\n");
      out.write("                        <path class=\"cls-1\" d=\"M56,38.32c-2.74,2.12-5.79,2.49-7.98,2.49h-1.99c.05,.94-.01,2.87,.25,3.31,2.17,1.23,6.85,2.45,9.56,3.19,4.28-1.32,6.82-3.13,9-5.42-6.07-.46-7.88-2.17-8.84-3.57Z\" />\r\n");
      out.write("                    </g>\r\n");
      out.write("                </svg>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"contentView\">\r\n");
      out.write("                    <div class=\"DJ_title\">\r\n");
      out.write("                        <h5>철 스크랩 전문회사</h5>\r\n");
      out.write("                        <h1>(주)대지에스텍</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <form id=\"frmLogin\" action=\"/daejiM/login/loginChk.do\" method=\"post\">\r\n");
      out.write("                        <input type=\"text\" name=\"username\" id=\"usrid\" placeholder=\"ID\" maxlength=\"20\">\r\n");
      out.write("                        <input type=\"password\" name=\"password\" id=\"usrpw\" placeholder=\"Password\" maxlength=\"16\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- 로그인 실패문구 -->\r\n");
      out.write("                        <c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty SPRING_SECURITY_LAST_EXCEPTION}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                            <div style=\"color: red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope[\"SPRING_SECURITY_LAST_EXCEPTION\"].message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                            <c:remove var=\"SPRING_SECURITY_LAST_EXCEPTION\" scope=\"session\" />\r\n");
      out.write("                        </c:if>\r\n");
      out.write("\r\n");
      out.write("                        <label for=\"saveID\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"saveID\" id=\"saveID\">\r\n");
      out.write("                            아이디 저장\r\n");
      out.write("                        </label>\r\n");
      out.write("\r\n");
      out.write("                        <input name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"button\" id=\"btnLogin\">로그인</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div> <!-- #contentView -->\r\n");
      out.write("            </main> <!-- #mainWrap -->\r\n");
      out.write("        </div> <!-- #wrap -->\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
