/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2026-08-10 03:08:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/daejist7/tomcat/webapps/scm/WEB-INF/lib/spring-security-taglibs-5.7.1.jar!/META-INF/security.tld", Long.valueOf(1652856986000L));
    _jspx_dependants.put("/WEB-INF/views/include/footer.jsp", Long.valueOf(1687502620000L));
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1694146608000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.7.1.jar", Long.valueOf(1732762432000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("        <meta property=\"og:type\" content=\"website\">\r\n");
      out.write("        <meta property=\"og:url\" content=\"https://example.co.kr\">\r\n");
      out.write("        <meta property=\"og:title\" content=\"Website Title\">\r\n");
      out.write("        <meta property=\"og:image\" content=\"https://meta-image.url\">\r\n");
      out.write("        <meta property=\"og:description\" content=\"Website Description\">\r\n");
      out.write("        <meta property=\"og:site_name\" content=\"Website Name\">\r\n");
      out.write("        <meta property=\"og:locale\" content=\"ko_KR\">\r\n");
      out.write("        \r\n");
      out.write("        <meta id=\"_csrf\" name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        <meta id=\"_csrf_name\" name=\"_csrf_name\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        <!-- OpenGraph Meta Tag -->\r\n");
      out.write("\r\n");
      out.write("        <title>(주) 대지에스텍</title>\r\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/scm/resources/images/icons/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/scm/resources/css/common/default.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/scm/resources/css/common/common.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/scm/resources/css/common/wanderface.css\">\r\n");
      out.write("        <!-- Global CSS -->\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js\"></script> <!-- jQuery CDN -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"/scm/resources/js/common/default.js\" async></script>\r\n");
      out.write("        <!-- Global JavaScript / jQuery -->\r\n");
      out.write("\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("            <script src=\"./resources/js/common/html5shiv.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("    </head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <a href=\"#mainWrap\" id=\"skipToMain\" tabindex=\"0\">Skip To Main Contents</a> <!-- 메인 컨텐츠 영역으로 건너뛰기 (접근성) -->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"wrap\">\r\n");
      out.write("            <header id=\"headPrimary\">\r\n");
      out.write("                <nav id=\"navPrimary\" role=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("                </nav>\r\n");
      out.write("            </header> <!-- #headPrimary -->\r\n");
      out.write("\r\n");
      out.write("            <main id=\"mainWrap\" role=\"main\">\r\n");
      out.write("                <link rel=\"stylesheet\" type=\"text/css\" href=\"/scm/resources/css/main/login.css\">\r\n");
      out.write("                <!-- Per-Page CSS -->\r\n");
      out.write("\r\n");
      out.write("                <script type=\"text/javascript\" src=\"/scm/resources/js/main/login.js\" defer></script>\r\n");
      out.write("                <!-- Per-Page JavaScript -->\r\n");
      out.write("\r\n");
      out.write("                <div id=\"contentView\">\r\n");
      out.write("                    <div id=\"winLogin\">\r\n");
      out.write("                        <h2>\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"1em\" height=\"1em\"><path fill=\"none\" d=\"M0 0h24v24H0z\"/><path d=\"M7 10h13a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V11a1 1 0 0 1 1-1h1V9a7 7 0 0 1 13.262-3.131l-1.789.894A5 5 0 0 0 7 9v1zm-2 2v8h14v-8H5zm5 3h4v2h-4v-2z\"/></svg>\r\n");
      out.write("                            로그인\r\n");
      out.write("                        </h2>\r\n");
      out.write("                        <form id=\"frmLogin\" class=\"clr_fix\" method=\"post\" action=\"/scm/login/loginChk.do\">\r\n");
      out.write("                            <div class=\"input_container\">\r\n");
      out.write("                                <div class=\"line_protector\">\r\n");
      out.write("                                    <label for=\"txtID\">아이디</label>\r\n");
      out.write("                                    <fieldset data-form-object=\"input-wrapper\">\r\n");
      out.write("                                        <input type=\"text\" name=\"username\" id=\"txtID\" placeholder=\"아이디\">\r\n");
      out.write("                                        <legend>아이디</legend>\r\n");
      out.write("                                    </fieldset>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"line_protector\">\r\n");
      out.write("                                    <label for=\"txtPW\">비밀번호</label>\r\n");
      out.write("                                    <fieldset data-form-object=\"input-wrapper\">\r\n");
      out.write("                                        <input type=\"password\" name=\"password\" id=\"txtPW\" placeholder=\"비밀번호\">\r\n");
      out.write("                                        <legend>비밀번호</legend>\r\n");
      out.write("                                    </fieldset>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"button\" id=\"btnLogin\">LOGIN</button>\r\n");
      out.write("                            <input name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        </form>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t\t<!-- 로그인 실패문구 -->\r\n");
      out.write("\t                    <c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty SPRING_SECURITY_LAST_EXCEPTION}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t                        <div style=\"color: red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope[\"SPRING_SECURITY_LAST_EXCEPTION\"].message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t                        <c:remove var=\"SPRING_SECURITY_LAST_EXCEPTION\" scope=\"session\" />\r\n");
      out.write("\t                    </c:if>\r\n");
      out.write("\t                    <!-- 로그인 실패문구 -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> <!-- #contentView -->\r\n");
      out.write("            </main> <!-- #mainWrap -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<footer id=\"footPrimary\">\r\n");
      out.write("\r\n");
      out.write("            </footer> <!-- #footPrimary -->\r\n");
      out.write("        </div> <!-- #wrap -->\r\n");
      out.write("\r\n");
      out.write("        <aside id=\"toolTip\">\r\n");
      out.write("            <p data-tooltip-text></p>\r\n");
      out.write("        </aside> <!-- #toolTip -->\r\n");
      out.write("\r\n");
      out.write("        <dialog id=\"winModal\" data-layer-type=\"modal\">\r\n");
      out.write("            <p></p>\r\n");
      out.write("            <h2></h2>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"button\" data-modal-close>닫기</button>\r\n");
      out.write("        </dialog>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
